theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = true
bitrate = false
ip = false
speed_up = false
speed_down = false
graph_up = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
show_percentage = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 1
good = 35
format = "{max}°"
chip = "*-isa-*"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "bluetooth"
mac = "98:09:CF:FE:72:7B"

[[block]]
block = "bluetooth"
mac = "DC:2C:26:A4:97:20"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
device = "DisplayDevice"

# This dumps "us,ru,az".
# [[block]]
# block = "keyboard_layout"
# driver = "localebus"

# [[block]]
# block = "custom"
# command = "xkblayout-state print %s"
# interval = 0.5

[[block]]
block = "time"
interval = 1
format = "%a %Y-%m-%d %T"
