#!/usr/bin/env fish
sudo ip netns exec protected sudo -u $USER -i \
    XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
    WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    DISPLAY=$DISPLAY \
    SWAYSOCK=$SWAYSOCK \
    XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP \
    XDG_SESSION_DESKTOP=$XDG_SESSION_DESKTOP \
    XDG_SESSION_TYPE=$XDG_SESSION_TYPE
