# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  programs.i3status-rust = {
    networkInterface = "wlp170s0";
  };

  boot = {
    extraModulePackages = [ ];
    kernelModules = [ "kvm-intel" ];
    kernelParams = [ "mem_sleep_default=deep" ];
    loader.systemd-boot.enable = true;
    initrd = {
      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      luks.devices."crypted".device = "/dev/disk/by-uuid/74cf5bcb-f6a5-4410-8247-4a04ffe30826";
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/crypted";
      fsType = "btrfs";
    };

    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
  };

  hardware.firmware = [ pkgs.unstable.firmwareLinuxNonfree ];

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "21.11";
  services.xserver = {
    videoDrivers = [ "modesetting" ];
    # DPI overrides this.
    monitorSection = ''
      DisplaySize 285 190 # mm.
    '';
    dpi = 150;
    displayManager.gdm.enable = true;
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  swapDevices = [{ label = "swap"; }];
}
